<?php

/**
 * @file
 * Provide helper for authentication user
 */

/**
 * Implements hook_menu().
 */
function cgangs_login_menu() {
  $items = array();
  $items['auth/user'] = array(
    'title' => 'Set your email and password',
    'description' => 'This page just for the third party authentication user.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cgangs_login_user'),
    'access callback' => 'cgangs_login_auth_user',
  );
  return $items;
}

/**
 * Implements hook_user_login().
 */
function cgangs_login_user_login(&$edit, $account) {
  if ($account->mail == '') {
    drupal_goto('auth/user');
  }
}

function cgangs_login_user($form, &$form_state) {
  $form['mail'] = array(
    '#type' => 'textfield',
    '#title' => t('Email'),
    '#default_value' => '',
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );

  $form['pass'] = array(
    '#type' => 'password_confirm',
    '#size' => 25,
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}

/**
 * 用户邮箱密码验证
 */
function cgangs_login_user_validate($form, &$form_state) {
  // Trim whitespace from mail, to prevent confusing 'e-mail not valid'
  // warnings often caused by cutting and pasting.
  $mail = trim($form_state['values']['mail']);
  form_set_value($form['mail'], $mail, $form_state);

  // Validate the e-mail address, and check if it is taken by an existing user.
  if ($error = user_validate_mail($form_state['values']['mail'])) {
    form_set_error('mail', $error);
  }
  elseif ((bool) db_select('users')->fields('users', array('uid'))->condition('uid', $account->uid, '<>')->condition('mail', db_like($form_state['values']['mail']), 'LIKE')->range(0, 1)->execute()->fetchField()) {
    // Format error message dependent on whether the user is logged in or not.
    if ($GLOBALS['user']->uid) {
      form_set_error('mail', t('The e-mail address %email is already taken.', array('%email' => $form_state['values']['mail'])));
    }
    else {
      form_set_error('mail', t('The e-mail address %email is already registered. <a href="@password">Have you forgotten your password?</a>', array('%email' => $form_state['values']['mail'], '@password' => url('user/password'))));
    }
  }
}

/**
 * 用户邮箱密码提交
 */
function cgangs_login_user_submit($form, &$form_state) {
  $mail = $form_state['values']['mail'];
  $pass = $form_state['values']['pass'];

  $edit = array(
    'mail' => $mail,
    'pass' => $pass,
  );

  global $user;
  $account = user_load($user->uid);
  user_save($account, $edit);
  drupal_set_message(t('Your account have updated.'), 'status', FALSE);
  drupal_goto('user');
}

/**
 * 验证用户是否设置有邮箱
 * @return bool
 */
function cgangs_login_auth_user() {
  global $user;
  if ($user->uid != 0 && $user->mail == '') {
    return TRUE;
  }

  return FALSE;
}
